spring:
  config:
    name: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/organizer2
    username: tester
    password: tester
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update